### ISSUE TITLE
Plugin panel does not display properly in Safari

### ISSUE THREAD

**Issue by cptserial** [Salandora/OctoPrint-SystemCommandEditor#4]
Hi. Thank you for this plugin, it is really awesome.

I have been having this bug for awhile, so I don't think it started in the most recent Safari update. When I go to Settings and choose System Command Editor, most of the interface is hidden. If I place my cursor perpendicular to the heading and scroll, I can scroll down and see a small slice of the interface at a time. I have attached screenshots to illustrate if this explanation doesn't make sense. Your other plugin, Custom Control Editor, works perfectly.

I am running Mac OS X 10.11.3 with Safari 9.0.3.

![system_command_editor_on _open](https://cloud.githubusercontent.com/assets/5551724/12961103/9486e98c-cff3-11e5-9dbd-b45ce34dff9e.png)
![sysem_command_editor_scrolled_down](https://cloud.githubusercontent.com/assets/5551724/12961120/b4655b58-cff3-11e5-8066-36867297c606.png)
![custom_control_editor_on_open](https://cloud.githubusercontent.com/assets/5551724/12961110/a28b7750-cff3-11e5-8457-72e7aec28b3f.png)

**Comment by Salandora** [comment]
Alright I'll check that when I have some time, propebly not before the 20th of February, sorry.
I would need somehelp with this, because I do not have a Mac or something to run Safari.

**Comment by cptserial** [comment]
No problem! Thank you for taking a look at it when you have the time. Just let me know anything you need me to do.

**Comment by JohnnyricoMC** [comment]
When using the safari web inspector or another functionally similar tool to remove "scrollable" from `<div class="tab-content span9 scrollable" id="settings_dialog_content">` , becoming `<div class="tab-content span9" id="settings_dialog_content">`, the system command editor becomes fully accessible for me:

before:
<img width="562" alt="screen shot 2016-07-15 at 02 01 03" src="https://cloud.githubusercontent.com/assets/1798635/16859548/09bbf60a-4a30-11e6-8b9b-9eea16cb8d03.png">

after:
<img width="489" alt="screen shot 2016-07-15 at 02 00 10" src="https://cloud.githubusercontent.com/assets/1798635/16859540/f6b43112-4a2f-11e6-83c0-4ca0e6712a17.png">

result:
<img width="991" alt="screen shot 2016-07-15 at 01 59 35" src="https://cloud.githubusercontent.com/assets/1798635/16859552/10b1b60c-4a30-11e6-90ef-a764016517b7.png">


Based on this, I think the problem might actually be an Octoprint issue rather than one in the plug-in. Just thought I'd report this finding.

**Comment by OutsourcedGuru** [comment]
Same here. Since people are talking about it on the OctoPrint forum as well, I've pointed them here and I'm linking that post [here](https://discourse.octoprint.org/t/system-command-editor-plugin-not-working/956/6?u=outsourcedguru).

**Comment by OutsourcedGuru** [comment]
Fixed in [PR](https://github.com/Salandora/OctoPrint-SystemCommandEditor/pull/12) and it's been merged, so this should be closed soon enough.

**Comment by Salandora** [comment]
Alright I pushed a new release and hopefully this will fix this problem.

Will close the issue in hope it can stay closed.
If the problem still appears feel free to open a new issue or comment here, I'll reopen it then.

Also here too a special thank you to you @OutsourcedGuru for fixing this bug.
